MONGODB_HOST = '34.94157.136'
MONGODB_PORT = 27017
MONGODB_USER = 'class'
MONGODB_PASS = 'CPSC313'
MONGODB_AUTH_SOURCE = 'cpsc313'
MONGODB_CLASS_DB = 'cpsc313'
MONGODB_CLASS_ROOM_LIST = 'rooms'
MONGODB_CLASS_USERS = 'users'
DEFAULT_PUBLIC_ROOM = 'general'
DEFAULT_ROOM_LIST_NAME = 'main'
DEFAULT_USER_LIST_NAME = 'global'


